In [1]:
import re
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.graphics.tsaplots as tsa_plots
from statsmodels.tsa.arima_model import ARIMA
import seaborn as sns
import requests
from bs4 import BeautifulSoup

### 91 days T-bill

In [2]:
tbill_91= pd.read_excel(r"D:\TASK\CP rates\MCLR\RBIB Table No. 25 _ Auctions of Government of India Treasury Bills - 91 days.xlsx")
#tbill_91= pd.read_excel(r"D:\TASK\CP rates\MCLR\HBS Table No. 213 _ Auctions of 91-Day Government of India Treasury Bills.xlsx")
tbill_91.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,Auctions of Government of India 91- Day Treasu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date of Auction,Date of Issue,Notified Amount(Rupees Crores),Bids Received,NaN,NaN,Bids Accepted,NaN,NaN,Total Issue (Rupees Crore) (8+9),Cut-off Price (Rupees),Implicit Yield at Cut-off Price (Per cent),Weighted Avg. Price (Rs.),Weighted Avg Yield (per cent)
3,NaN,NaN,NaN,NaN,Number,Total Face Value (Rupees Crores),NaN,Number,Total Face Value (Rupees Crores),NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,Competitive,Non-Competitive,NaN,Competitive,Non-Competitive,NaN,NaN,NaN,NaN,NaN

In [3]:
tbill_91= tbill_91.iloc[6:500,[1,12]]
tbill_91= tbill_91.rename(columns={tbill_91.columns[0]: 'Date', tbill_91.columns[1]: '91d yield'})
tbill_91=tbill_91.dropna(subset='Date')
tbill_91=tbill_91.drop_duplicates()
tbill_91.loc[tbill_91['91d yield']=="-",'91d yield']=np.nan
tbill_91['Date']=pd.to_datetime(tbill_91['Date'])
tbill_91= tbill_91.sort_values(by='Date',ascending=True)
tbill_91= tbill_91.reset_index(drop=True)
tbill_91.head()

        Date 91d yield
0 2016-02-03    7.3521
1 2016-02-10    7.3521
2 2016-02-17    7.3521
3 2016-02-24       NaN
4 2016-03-02    7.2689

### 182 days T-bill

In [11]:
tbill_182= pd.read_excel(r"D:\TASK\CP rates\MCLR\RBIB Table No. 25 _ Auctions of Government of India Treasury Bills - 182 days.xlsx")
tbill_182.head(3)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,Auctions of Government of India 182- Day Treas...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date of Auction,Date of Issue,Notified Amount(Rupees Crores),Bids Received,NaN,NaN,Bids Accepted,NaN,NaN,Total Issue (Rupees Crore) (8+9),Cut-off Price (Rupees),Implicit Yield at Cut-off Price (Per cent),Weighted Avg. Price (Rs.),Weighted Avg Yield (per cent)

In [12]:
tbill_182= tbill_182.iloc[6:500,[1,12]]
tbill_182= tbill_182.rename(columns= {tbill_182.columns[0]: 'Date', tbill_182.columns[1]: '182d yield'})
tbill_182= tbill_182.dropna(subset= 'Date')
tbill_182= tbill_182.drop_duplicates()
tbill_182.loc[tbill_182['182d yield']=="-",'182d yield']=np.nan
tbill_182['Date']= pd.to_datetime(tbill_182['Date'])
tbill_182= tbill_182.sort_values(by='Date', ascending=True)
tbill_182= tbill_182.reset_index(drop=True)
tbill_182.tail()

          Date 182d yield
489 2025-07-16     5.5399
490 2025-07-23     5.5291
491 2025-07-30     5.5206
492 2025-08-06     5.5475
493 2025-08-13     5.5678

### 364 days T-bill

In [9]:
tbill_364= pd.read_excel(r"D:\TASK\CP rates\MCLR\RBIB Table No. 25 _ Auctions of Government of India Treasury Bills - 364 days.xlsx")
tbill_364.head(3)

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,NaN,Auctions of Government of India 364- Day Treas...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date of Auction,Date of Issue,Notified Amount(Rupees Crores),Bids Received,NaN,NaN,Bids Accepted,NaN,NaN,Total Issue (Rupees Crore) (8+9),Cut-off Price (Rupees),Implicit Yield at Cut-off Price (Per cent),Weighted Avg. Price (Rs.),Weighted Avg Yield (per cent)

In [10]:
tbill_364= tbill_364.iloc[6:500,[1,12]]
tbill_364= tbill_364.rename(columns= {tbill_364.columns[0]:'Date', tbill_364.columns[1]:'364d yield'})
tbill_364= tbill_364.dropna(subset= 'Date')
tbill_364= tbill_364.drop_duplicates()
tbill_364.loc[tbill_364['364d yield']=="-",'364d yield']=np.nan
tbill_364['Date']= pd.to_datetime(tbill_364['Date'])
tbill_364= tbill_364.sort_values(by='Date', ascending=True)
tbill_364= tbill_364.reset_index(drop=True)
tbill_364.head()

        Date 364d yield
0 2014-05-28     8.6959
1 2014-06-11     8.6012
2 2014-06-25     8.6959
3 2014-07-09     8.6722
4 2014-07-23     8.6959

In [13]:
tbill= tbill_91.merge(tbill_182, how='left', on='Date')
tbill.head()

        Date 91d yield 182d yield
0 2016-02-03    7.3521        NaN
1 2016-02-10    7.3521     7.2738
2 2016-02-17    7.3521        NaN
3 2016-02-24       NaN        NaN
4 2016-03-02    7.2689        NaN

In [14]:
tbills= tbill.merge(tbill_364, how='left', on='Date')
tbills.head()

        Date 91d yield 182d yield 364d yield
0 2016-02-03    7.3521        NaN       7.27
1 2016-02-10    7.3521     7.2738        NaN
2 2016-02-17    7.3521        NaN     7.2816
3 2016-02-24       NaN        NaN        NaN
4 2016-03-02    7.2689        NaN     7.1893

In [15]:
tbills= tbills.loc[tbills['Date'] >= '2020-01-01']
tbills= tbills.ffill()
print(tbills.shape)
tbills.head()

(290, 4)

          Date  91d yield  182d yield  364d yield
204 2020-01-01     4.9386      5.2204      5.2998
205 2020-01-08     5.0525      5.2098      5.2871
206 2020-01-15     5.1381      5.2267      5.2998
207 2020-01-22     5.1167      5.2267      5.2887
208 2020-01-29     5.1266      5.2396      5.2890

In [16]:
tbills['month_year']= tbills['Date'].dt.strftime('%b-%Y')
tbills.tail()

          Date  91d yield  182d yield  364d yield month_year
489 2025-07-16     5.3851      5.5399      5.5924   Jul-2025
490 2025-07-23     5.3872      5.5291      5.5701   Jul-2025
491 2025-07-30     5.3970      5.5206      5.5673   Jul-2025
492 2025-08-06     5.4597      5.5475      5.5790   Aug-2025
493 2025-08-13     5.4902      5.5678      5.5898   Aug-2025

In [17]:
tbills_monthly_avg= tbills.groupby('month_year')[['91d yield', '182d yield', '364d yield']].mean()
tbills_monthly_avg= tbills_monthly_avg.reset_index()
tbills_monthly_avg['Date']= pd.to_datetime(tbills_monthly_avg['month_year'], format='%b-%Y') 
tbills_monthly_avg.head()

  month_year  91d yield  182d yield  364d yield       Date
0   Apr-2020   3.954725    4.052650    4.110525 2020-04-01
1   Apr-2021   3.339550    3.544475    3.742325 2021-04-01
2   Apr-2022   3.946875    4.376325    4.751800 2022-04-01
3   Apr-2023   6.812025    7.020725    7.062950 2023-04-01
4   Apr-2024   6.885550    7.028375    7.055400 2024-04-01

### Adding Repo

In [18]:
monetory= pd.read_excel(r"D:\TASK\CP rates\Cogencis data\Major Monetary Policy Rates.xlsx")
monetry=monetory.iloc[7:200,1:]
monetry.rename(columns={'Unnamed: 1':'Date', 'Unnamed: 2':'Bank Rate', 'Unnamed: 3':'Repo',
                        'Unnamed: 4':'Reverse Repo', 'Unnamed: 5':'Standing Deposit Facility Rate', 
                        'Unnamed: 6':'Marginal Standing Facility Rate', 'Unnamed: 7':'Cash Reserve Ratio',
                        'Unnamed: 8':'Statutory Liquidity Ratio'}, inplace=True)
monetory.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,NaN,MAJOR MONETARY POLICY RATES AND RESERVE REQUIR...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,(Per cent),NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,Effective Date\n,Bank Rate,Fix Range LAF Rates,NaN,Standing Deposit Facility (SDF) Rate,Marginal Standing Facility (MSF) Rate,Cash Reserve Ratio (CRR),Statutory Liquidity Ratio (SLR)

In [19]:
monetry= monetry.sort_values(by='Date',ascending=True)
monetry= monetry.replace('-',np.nan)
monetry= monetry.ffill()
monetry= monetry.bfill()
monetry.head()

,Date,Bank Rate,Repo,Reverse Repo,Standing Deposit Facility Rate,Marginal Standing Facility Rate,Cash Reserve Ratio,Statutory Liquidity Ratio
199,1993-04-17,11.0,9.0,6.75,3.75,8.25,14.5,37.50
198,1993-05-15,11.0,9.0,6.75,3.75,8.25,14,37.50
197,1993-08-21,11.0,9.0,6.75,3.75,8.25,14,37.50
196,1993-09-18,11.0,9.0,6.75,3.75,8.25,14,37.25
195,1993-10-16,11.0,9.0,6.75,3.75,8.25,14,34.75

In [20]:
monetry['Cash Reserve Ratio']= monetry['Cash Reserve Ratio'].astype('float')
monetry['Date']=pd.to_datetime(monetry['Date'],format="%d-%m-%Y")
monetry[monetry.duplicated()==True]

Empty DataFrame
Columns: [Date, Bank Rate, Repo, Reverse Repo, Standing Deposit Facility Rate, Marginal Standing Facility Rate, Cash Reserve Ratio, Statutory Liquidity Ratio]
Index: []

In [21]:
monetry=monetry.drop_duplicates()
monetry1= monetry.set_index('Date')
monetry_d= monetry1.resample('D').ffill()
monetry_d.head()

,Bank Rate,Repo,Reverse Repo,Standing Deposit Facility Rate,Marginal Standing Facility Rate,Cash Reserve Ratio,Statutory Liquidity Ratio
Date,,,,,,,
1993-04-17,11.0,9.0,6.75,3.75,8.25,14.5,37.5
1993-04-18,11.0,9.0,6.75,3.75,8.25,14.5,37.5
1993-04-19,11.0,9.0,6.75,3.75,8.25,14.5,37.5
1993-04-20,11.0,9.0,6.75,3.75,8.25,14.5,37.5
1993-04-21,11.0,9.0,6.75,3.75,8.25,14.5,37.5

In [22]:
monetry_d= monetry_d.reset_index('Date')
monetry_d= monetry_d[['Date','Repo']]
monetry_d['month_year']= monetry_d['Date'].dt.strftime('%b-%Y')  
#monetry_d['Date']= pd.to_datetime(monetry['Date'])
#monetry_d= monetry_d.loc[monetry_d['Date'] >= '2020-01-01']
print(monetry_d.shape)
monetry_d.head()

(11744, 3)

        Date  Repo month_year
0 1993-04-17   9.0   Apr-1993
1 1993-04-18   9.0   Apr-1993
2 1993-04-19   9.0   Apr-1993
3 1993-04-20   9.0   Apr-1993
4 1993-04-21   9.0   Apr-1993

In [23]:
# combine the base cut-off yield dataframe with monetry fileds

dfrs= pd.merge(tbills_monthly_avg, monetry_d, on='Date', how='left')
dfrs=dfrs.drop('month_year_y', axis=1)
dfrs= dfrs.rename(columns= {'month_year_x': 'month_year'})
print(dfrs.shape)
dfrs.head(5)

(68, 6)

  month_year  91d yield  182d yield  364d yield       Date  Repo
0   Apr-2020   3.954725    4.052650    4.110525 2020-04-01   4.4
1   Apr-2021   3.339550    3.544475    3.742325 2021-04-01   4.0
2   Apr-2022   3.946875    4.376325    4.751800 2022-04-01   4.0
3   Apr-2023   6.812025    7.020725    7.062950 2023-04-01   6.5
4   Apr-2024   6.885550    7.028375    7.055400 2024-04-01   6.5

In [24]:
dfrs.isnull().sum()

month_year    0
91d yield     0
182d yield    0
364d yield    0
Date          0
Repo          2
dtype: int64

### Adding CPI Inflation

In [25]:
cpi_df= pd.read_excel(r"D:\TASK\CP rates\Cogencis data\CPI monthly data.xlsx")
print(cpi_df.shape)
cpi_df.head(3)

(342, 23)

,"Consumer Price Index (CPI): Combined, Urban and Rural: General Index, Groups and Subgroups : Base Year 2012 : Index numbers",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22
0,Year,Frequency,General Index,General Index,General Index,Food and beverages,Food and beverages,Food and beverages,"Pan, tobacco and intoxicants","Pan, tobacco and intoxicants",...,Clothing & footwear,Housing,Housing,Housing,Fuel & light,Fuel & light,Fuel & light,Miscellaneous,Miscellaneous,Miscellaneous
1,NaN,NaN,Combined,Urban,Rural,Combined,Urban,Rural,Combined,Urban,...,Rural,Combined,Urban,Rural,Combined,Urban,Rural,Combined,Urban,Rural
2,Weight,NaN,100,100,100,45.86,36.29,54.18,2.38,1.36,...,7.36,10.07,21.67,0,6.84,5.58,7.94,28.32,29.53,27.26

In [26]:
cpi= cpi_df.iloc[3:,[0,1,2]]
cpi.rename(columns={cpi.columns[0]: 'Date', cpi.columns[1]: 'Freq', cpi.columns[2]: 'CPI Inflation'}, inplace=True)
cpi= cpi.loc[cpi['Freq']=='M']
cpi= cpi.drop('Freq', axis=1)

cpi["CPI Inflation"]= cpi["CPI Inflation"].ffill()
cpi["CPI Inflation"]= cpi["CPI Inflation"].bfill()

cpi['Date']= cpi.apply(lambda row: str(row['Date'])[0:4]+'-'+str(row['Date'])[4:6]+'-'+str(row['Date'])[6:], axis=1)
cpi= cpi.loc[cpi['Date']> '2009-12-31']
cpi= cpi.sort_values('Date', ascending=True)
print(cpi.shape)
cpi.head(5)

(176, 2)

         Date  CPI Inflation
3  2011-01-31           89.5
4  2011-02-28           88.4
5  2011-03-31           88.4
6  2011-04-30           89.1
7  2011-05-31           89.8

In [27]:
cpi['Date']= pd.to_datetime(cpi['Date'], format='%Y-%m-%d')
# adding the month_year column in cpi based on date column
cpi['month_year'] = cpi['Date'].dt.strftime('%b-%Y')
cpi.head()

# adding the month_year column in dfs based on date column
dfrs['month_year'] = dfrs['Date'].dt.strftime('%b-%Y')

# Joining the CPI data with original data based on month-year column
dfs= dfrs.merge(cpi[['CPI Inflation','month_year']], how='left', on='month_year')
dfs= dfs.loc[dfs['Date']> '2020-04-01']

# drop the month-year column
#dfs= dfs.drop('month_year', axis=1)
dfs= dfs.ffill()
print(dfs.shape)
dfs.head()

(64, 7)

,month_year,91d yield,182d yield,364d yield,Date,Repo,CPI Inflation
1,Apr-2021,3.339550,3.544475,3.742325,2021-04-01,4.00,157.8
2,Apr-2022,3.946875,4.376325,4.751800,2022-04-01,4.00,170.1
3,Apr-2023,6.812025,7.020725,7.062950,2023-04-01,6.50,178.1
4,Apr-2024,6.885550,7.028375,7.055400,2024-04-01,6.50,186.7
5,Apr-2025,6.015100,6.057680,6.053060,2025-04-01,6.25,192.6

In [28]:
dfs= dfs.sort_values(by='Date', ascending=True)
dfs.tail()

,month_year,91d yield,182d yield,364d yield,Date,Repo,CPI Inflation
5,Apr-2025,6.015100,6.057680,6.05306,2025-04-01,6.25,192.6
52,May-2025,5.762700,5.764775,5.76995,2025-05-01,6.00,193.0
40,Jun-2025,5.428975,5.506425,5.54205,2025-06-01,6.00,194.2
34,Jul-2025,5.385280,5.525360,5.57158,2025-07-01,6.50,196.0
11,Aug-2025,5.474950,5.557650,5.58440,2025-08-01,6.50,197.3

In [29]:
dfs.loc[dfs.index[-1],'Repo']=5.50
dfs.loc[dfs.index[-2],'Repo']=5.50
dfs.loc[dfs.index[-3],'Repo']=5.50
dfs.loc[dfs.index[-5],'Repo']=6.00
dfs.tail(6)

,month_year,91d yield,182d yield,364d yield,Date,Repo,CPI Inflation
46,Mar-2025,6.501125,6.585775,6.53635,2025-03-01,6.25,192.0
5,Apr-2025,6.015100,6.057680,6.05306,2025-04-01,6.00,192.6
52,May-2025,5.762700,5.764775,5.76995,2025-05-01,6.00,193.0
40,Jun-2025,5.428975,5.506425,5.54205,2025-06-01,5.50,194.2
34,Jul-2025,5.385280,5.525360,5.57158,2025-07-01,5.50,196.0
11,Aug-2025,5.474950,5.557650,5.58440,2025-08-01,5.50,197.3

### Indian bank, ICICI and BOB MCLR

In [328]:
ib_df= pd.read_excel(r"D:\TASK\CP rates\MCLR\Bank_of_Baroda_MCLR.xlsx")
ib_df['month_year']= ib_df['Effective Date '].dt.strftime('%b-%Y')
print(ib_df.shape)
ib_df.head()

(113, 7)

  Effective Date   Over Night    1M    3M   6M   1 Year month_year
0      2016-04-12        9.00  9.05  9.05  9.05    9.25   Apr-2016
1      2016-05-12        9.05  9.10  9.20  9.25    9.30   May-2016
2      2016-06-12        9.15  9.20  9.30  9.35    9.40   Jun-2016
3      2016-07-12        9.15  9.20  9.30  9.35    9.40   Jul-2016
4      2016-08-12        9.15  9.20  9.30  9.35    9.40   Aug-2016

In [329]:
dfs_ib= dfs.merge(ib_df[['month_year', '1 Year']], how='left', on='month_year')
dfs_ib= dfs_ib.rename(columns={'1 Year': 'MCLR'})
dfs_ib['MCLR']= dfs_ib['MCLR']
#dfs_ib['MCLR']= dfs_ib['MCLR']*100  # if 1Year MCLR value in % use this line   
dfs_ib.head()

,month_year,91d yield,182d yield,364d yield,Date,Repo,CPI Inflation,MCLR
0,May-2020,3.368250,3.621600,3.654900,2020-05-01,4.4,150.9,7.80
1,Jun-2020,3.311025,3.463500,3.558075,2020-06-01,4.0,151.8,7.65
2,Jul-2020,3.217400,3.372500,3.456460,2020-07-01,4.0,153.9,7.60
3,Aug-2020,3.234050,3.426525,3.540425,2020-08-01,4.0,154.7,7.60
4,Sep-2020,3.275150,3.526025,3.655025,2020-09-01,4.0,156.4,7.55

### G-Sec yields

In [330]:
g_sec= pd.read_excel("D:\TASK\CP rates\MCLR\Yield_on_Residual_Maturity_of_Government_of_India_Dated_Securities_in_Secondary_Market\Yield_on_Residual_maturity_G-sec.xlsx")
g_secs= g_sec.iloc[3:257,[0, 5, 13, 21, 41]]
g_sec1= g_sec.iloc[257:, [0, 2, 10, 18, 38]]
g_secs= g_secs.rename(columns={g_secs.columns[0]:'Date', g_secs.columns[1]:'1y G-sec', g_secs.columns[2]:'3y G-sec', 
                    g_secs.columns[3]:'5y G-sec', g_secs.columns[4]:'10y G-sec'})

g_sec1= g_sec1.rename(columns={g_sec1.columns[0]:'Date', g_sec1.columns[1]:'1y G-sec', g_sec1.columns[2]:'3y G-sec', 
                    g_sec1.columns[3]:'5y G-sec', g_sec1.columns[4]:'10y G-sec'})
g_secs.head()

c:\Users\manirathinams\AppData\Local\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:79: UserWarning: Cell A269 is marked as a date but the serial value 20250630 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():
c:\Users\manirathinams\AppData\Local\anaconda3\Lib\site-packages\openpyxl\worksheet\_read_only.py:79: UserWarning: Cell A270 is marked as a date but the serial value 20250731 is outside the limits for dates. The cell will be treated as an error.
  for idx, row in parser.parse():

       Date 1y G-sec 3y G-sec 5y G-sec 10y G-sec
3  20030630      NaN      NaN      NaN       NaN
4  20030731      NaN      NaN      NaN       NaN
5  20030831      NaN      NaN      NaN       NaN
6  20030930      NaN      NaN      NaN       NaN
7  20031031      NaN      NaN      NaN       NaN

In [331]:
g_secs['Date']= pd.to_datetime(g_secs['Date'])
g_sec1['Date']= pd.to_datetime(g_sec1['Date'])
g_secs= g_secs.loc[g_secs['Date'] >= '2020-01-01']
g_secs['month_year']= g_secs['Date'].dt.strftime('%b-%Y')
g_sec1['month_year']= g_sec1['Date'].dt.strftime('%b-%Y')
g_secs.head(10)

          Date 1y G-sec 3y G-sec 5y G-sec 10y G-sec month_year
202 2020-01-31     5.66     6.21     6.40      6.60   Jan-2020
203 2020-02-29     5.33     5.66     5.87      6.37   Feb-2020
204 2020-03-31     4.97     5.40     5.58      6.14   Mar-2020
205 2020-04-30     3.93     4.73     5.15      6.11   Apr-2020
206 2020-05-31     3.98     4.39     4.97      5.98   May-2020
207 2020-06-30     3.73     4.35     5.07      5.99   Jun-2020
208 2020-07-31     3.58     4.73     4.99      5.84   Jul-2020
209 2020-08-31     3.75     4.99     5.48      6.08   Aug-2020
210 2020-09-30     3.71     4.95     5.39      6.02   Sep-2020
211 2020-10-31     3.47     4.63     5.17      5.88   Oct-2020

In [332]:
g_secs.tail()

          Date 1y G-sec 3y G-sec 5y G-sec 10y G-sec month_year
252 2024-03-31     7.08     7.05     7.05      7.06   Mar-2024
253 2024-04-30     7.08     7.19     7.21      7.19   Apr-2024
254 2024-05-31     7.00     7.04     7.05      7.04   May-2024
255 2024-06-30     6.94     6.98     7.02      7.01   Jun-2024
256 2024-07-31     6.79     6.84     6.85      6.93   Jul-2024

In [333]:
g_sec1.tail(5)

          Date 1y G-sec 3y G-sec 5y G-sec 10y G-sec month_year
264 2025-03-31     6.56     6.53     6.57      6.66   Mar-2025
265 2025-04-30     6.13     6.15     6.16      6.40   Apr-2025
266 2025-05-31     5.81     5.97     6.00      6.31   May-2025
267        NaT      5.6     5.83      5.9      6.33        NaN
268        NaT     5.57     5.83     6.05      6.37        NaN

In [334]:
G_Sec = pd.concat([g_secs, g_sec1], axis=0, ignore_index=True)
G_Sec.tail()

         Date 1y G-sec 3y G-sec 5y G-sec 10y G-sec month_year
62 2025-03-31     6.56     6.53     6.57      6.66   Mar-2025
63 2025-04-30     6.13     6.15     6.16      6.40   Apr-2025
64 2025-05-31     5.81     5.97     6.00      6.31   May-2025
65        NaT      5.6     5.83      5.9      6.33        NaN
66        NaT     5.57     5.83     6.05      6.37        NaN

In [335]:
fnl= dfs_ib.merge(G_Sec[['1y G-sec','3y G-sec','5y G-sec','10y G-sec','month_year']], how='left', on='month_year')

fnl= fnl[['Date','month_year','Repo','CPI Inflation','91d yield','182d yield','364d yield', 
            '1y G-sec', '3y G-sec', '5y G-sec', '10y G-sec', 'MCLR']]

fnl= fnl.ffill()

fnl.head()

,Date,month_year,Repo,CPI Inflation,91d yield,182d yield,364d yield,1y G-sec,3y G-sec,5y G-sec,10y G-sec,MCLR
0,2020-05-01,May-2020,4.4,150.9,3.368250,3.621600,3.654900,3.98,4.39,4.97,5.98,7.80
1,2020-06-01,Jun-2020,4.0,151.8,3.311025,3.463500,3.558075,3.73,4.35,5.07,5.99,7.65
2,2020-07-01,Jul-2020,4.0,153.9,3.217400,3.372500,3.456460,3.58,4.73,4.99,5.84,7.60
3,2020-08-01,Aug-2020,4.0,154.7,3.234050,3.426525,3.540425,3.75,4.99,5.48,6.08,7.60
4,2020-09-01,Sep-2020,4.0,156.4,3.275150,3.526025,3.655025,3.71,4.95,5.39,6.02,7.55

In [336]:
fnl.tail(15)

,Date,month_year,Repo,CPI Inflation,91d yield,182d yield,364d yield,1y G-sec,3y G-sec,5y G-sec,10y G-sec,MCLR
49,2024-06-01,Jun-2024,6.50,190.2,6.829325,6.972650,6.996300,6.94,6.98,7.02,7.01,8.85
50,2024-07-01,Jul-2024,6.50,193.0,6.733060,6.845680,6.875640,6.79,6.84,6.85,6.93,8.90
51,2024-08-01,Aug-2024,6.50,193.0,6.630825,6.725375,6.724975,6.75,6.76,6.78,6.87,8.95
52,2024-09-01,Sep-2024,6.50,194.2,6.638150,6.724150,6.709500,6.65,6.69,6.69,6.78,8.95
53,2024-10-01,Oct-2024,6.50,196.8,6.469340,6.578420,6.563800,6.67,6.69,6.71,6.80,8.95
54,2024-11-01,Nov-2024,6.50,196.5,6.458550,6.639200,6.622025,6.70,6.75,6.77,6.84,9.00
55,2024-12-01,Dec-2024,6.50,195.4,6.474500,6.622150,6.606325,6.68,6.67,6.70,6.73,9.00
56,2025-01-01,Jan-2025,6.50,193.4,6.593020,6.702780,6.681300,6.63,6.70,6.74,6.75,9.00
57,2025-02-01,Feb-2025,6.50,192.5,6.451525,6.579750,6.549675,6.58,6.61,6.63,6.69,9.00
58,2025-03-01,Mar-2025,6.25,192.0,6.501125,6.585775,6.536350,6.56,6.53,6.57,6.66,9.00
59,2025-04-01,Apr-2025,6.00,192.6,6.015100,6.057680,6.053060,6.13,6.15,6.16,6.40,9.00
60,2025-05-01,May-2025,6.00,193.0,5.762700,5.764775,5.769950,5.81,5.97,6.00,6.31,8.95
61,2025-06-01,Jun-2025,5.50,194.2,5.428975,5.506425,5.542050,5.81,5.97,6.00,6.31,8.90
62,2025-07-01,Jul-2025,5.50,196.0,5.385280,5.525360,5.571580,5.81,5.97,6.00,6.31,8.90
63,2025-08-01,Aug-2025,5.50,197.3,5.474950,5.557650,5.584400,5.81,5.97,6.00,6.31,8.80

In [442]:
# Jul'24 to Sep'_24

fnl1= fnl[:-2]
fnl1.tail(15)

,Date,month_year,Repo,CPI Inflation,91d yield,182d yield,364d yield,1y G-sec,3y G-sec,5y G-sec,10y G-sec,MCLR
47,2024-04-01,Apr-2024,6.50,186.7,6.885550,7.028375,7.055400,7.08,7.19,7.21,7.19,8.85
48,2024-05-01,May-2024,6.50,187.7,6.937360,7.045240,7.061320,7.00,7.04,7.05,7.04,8.85
49,2024-06-01,Jun-2024,6.50,190.2,6.829325,6.972650,6.996300,6.94,6.98,7.02,7.01,8.85
50,2024-07-01,Jul-2024,6.50,193.0,6.733060,6.845680,6.875640,6.79,6.84,6.85,6.93,8.90
51,2024-08-01,Aug-2024,6.50,193.0,6.630825,6.725375,6.724975,6.75,6.76,6.78,6.87,8.95
52,2024-09-01,Sep-2024,6.50,194.2,6.638150,6.724150,6.709500,6.65,6.69,6.69,6.78,8.95
53,2024-10-01,Oct-2024,6.50,196.8,6.469340,6.578420,6.563800,6.67,6.69,6.71,6.80,8.95
54,2024-11-01,Nov-2024,6.50,196.5,6.458550,6.639200,6.622025,6.70,6.75,6.77,6.84,9.00
55,2024-12-01,Dec-2024,6.50,195.4,6.474500,6.622150,6.606325,6.68,6.67,6.70,6.73,9.00
56,2025-01-01,Jan-2025,6.50,193.4,6.593020,6.702780,6.681300,6.63,6.70,6.74,6.75,9.00
57,2025-02-01,Feb-2025,6.50,192.5,6.451525,6.579750,6.549675,6.58,6.61,6.63,6.69,9.00
58,2025-03-01,Mar-2025,6.25,192.0,6.501125,6.585775,6.536350,6.56,6.53,6.57,6.66,9.00
59,2025-04-01,Apr-2025,6.00,192.6,6.015100,6.057680,6.053060,6.13,6.15,6.16,6.40,9.00
60,2025-05-01,May-2025,6.00,193.0,5.762700,5.764775,5.769950,5.81,5.97,6.00,6.31,8.95
61,2025-06-01,Jun-2025,5.50,194.2,5.428975,5.506425,5.542050,5.81,5.97,6.00,6.31,8.90

### ARIMA Forecasting

In [443]:
from pmdarima import auto_arima
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [444]:
data= fnl1.set_index('Date')

# removing some unwanted columns
data= data.drop(['month_year'], axis=1) 
data.head(3)

,Repo,CPI Inflation,91d yield,182d yield,364d yield,1y G-sec,3y G-sec,5y G-sec,10y G-sec,MCLR
Date,,,,,,,,,,
2020-05-01,4.4,150.9,3.368250,3.6216,3.654900,3.98,4.39,4.97,5.98,7.80
2020-06-01,4.0,151.8,3.311025,3.4635,3.558075,3.73,4.35,5.07,5.99,7.65
2020-07-01,4.0,153.9,3.217400,3.3725,3.456460,3.58,4.73,4.99,5.84,7.60

In [445]:
# getting the month and day of the year columns

import calendar
def create_feature(df):
    df['quarter']=df.index.quarter
    df['Month']=df.index.month
    # df['Year']=df.index.year
    #df['dayofyear']=df.index.dayofyear
    # df['weekday']=df.index.dayofweek
    return df
# d.index.dayofweek #0=Monday , 1=Tuesday , 2=Wednesday
 
def encode_quarter_finQuarter(data):
    data.loc[data['quarter']==1,'quarter']='Q4'
    data.loc[data['quarter']==2,'quarter']='Q1'
    data.loc[data['quarter']==3,'quarter']='Q2'
    data.loc[data['quarter']==4,'quarter']='Q3'
    return data
def encode_finQuarter_num(data):
    data.loc[data['quarter']=='Q4','quarter']=4
    data.loc[data['quarter']=='Q1','quarter']=1
    data.loc[data['quarter']=='Q2','quarter']=2
    data.loc[data['quarter']=='Q3','quarter']=3
    return data

def Merging_feature_engg_with_data(h23):
    h23=create_feature(h23)
    h23=encode_quarter_finQuarter(h23)
    h23=encode_finQuarter_num(h23)
    h23['quarter']=h23['quarter'].astype('int')
    return h23

data =Merging_feature_engg_with_data(data)
data= data.ffill()
data.tail(4)

C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\3578216625.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Q4' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  data.loc[data['quarter']==1,'quarter']='Q4'

,Repo,CPI Inflation,91d yield,182d yield,364d yield,1y G-sec,3y G-sec,5y G-sec,10y G-sec,MCLR,quarter,Month
Date,,,,,,,,,,,,
2025-03-01,6.25,192.0,6.501125,6.585775,6.53635,6.56,6.53,6.57,6.66,9.00,4,3
2025-04-01,6.00,192.6,6.015100,6.057680,6.05306,6.13,6.15,6.16,6.40,9.00,1,4
2025-05-01,6.00,193.0,5.762700,5.764775,5.76995,5.81,5.97,6.00,6.31,8.95,1,5
2025-06-01,5.50,194.2,5.428975,5.506425,5.54205,5.81,5.97,6.00,6.31,8.90,1,6

In [446]:
from statsmodels.tsa.stattools import adfuller

# Perform the ADF test
def adf_test(timeseries):
    # Perform Dickey-Fuller test:
    adf_result = adfuller(timeseries, autolag='AIC')
    
    # Print ADF test results
    print('ADF Statistic: {:.4f}'.format(adf_result[0]))
    print('p-value: {:.4f}'.format(adf_result[1]))
    print('Critical Values:')
    for key, value in adf_result[4].items():
        print('\t{}: {:.4f}'.format(key, value))

# Assuming 'Yield' column is the one you want to test for stationarity
adf_test(data['MCLR'])

ADF Statistic: -1.4810
p-value: 0.5429
Critical Values:
	1%: -3.5485
	5%: -2.9128
	10%: -2.5941

The p-value 0.7499 is greater than 0.05 for a significance level of 5%, indicating rejects the H1-(alternate hypothesis) and accepting the H0-(null hypothesis). Therefore, the data is likely non-stationary. it might require differencing or other transformations to achieve stationarity.

In [447]:
data.columns

Index(['Repo', 'CPI Inflation', '91d yield', '182d yield', '364d yield',
       '1y G-sec', '3y G-sec', '5y G-sec', '10y G-sec', 'MCLR', 'quarter',
       'Month'],
      dtype='object')

In [448]:
data.describe()

,Repo,CPI Inflation,91d yield,182d yield,364d yield,MCLR,quarter,Month
count,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000,62.000000
mean,5.321774,175.406452,5.265922,5.502393,5.617989,8.140323,2.451613,6.467742
std,1.158349,13.884428,1.566754,1.545660,1.479510,0.683760,1.140570,3.429466
min,4.000000,150.900000,3.056450,3.326250,3.423475,7.300000,1.000000,1.000000
25%,4.000000,162.975000,3.425808,3.637425,3.810110,7.400000,1.000000,4.000000
50%,5.900000,176.500000,5.932750,6.198565,6.395965,8.175000,2.000000,6.000000
75%,6.500000,186.300000,6.730651,6.876537,6.915664,8.800000,3.000000,9.000000
max,6.500000,196.800000,7.010825,7.291660,7.344280,9.000000,4.000000,12.000000

In [449]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 62 entries, 2020-05-01 to 2025-06-01
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Repo           62 non-null     float64
 1   CPI Inflation  62 non-null     float64
 2   91d yield      62 non-null     float64
 3   182d yield     62 non-null     float64
 4   364d yield     62 non-null     float64
 5   1y G-sec       62 non-null     object
 6   3y G-sec       62 non-null     object
 7   5y G-sec       62 non-null     object
 8   10y G-sec      62 non-null     object
 9   MCLR           62 non-null     float64
 10  quarter        62 non-null     int32
 11  Month          62 non-null     int32
dtypes: float64(6), int32(2), object(4)
memory usage: 5.8+ KB

In [450]:
# List of columns that are currently 'object' and need to be numeric
gsec_cols_to_convert = ['1y G-sec', '3y G-sec', '5y G-sec', '10y G-sec']

for col in gsec_cols_to_convert:
    # Convert to string first to use .str accessor, then replace commas and convert to numeric.
    # errors='coerce' will turn any values that cannot be parsed into numbers (e.g., actual non-numeric text) into NaN.
    # It's crucial to handle these NaNs if they appear, though your Non-Null count suggests they won't from the original data.
    data[col] = pd.to_numeric(data[col].astype(str).str.replace(',', ''), errors='coerce')

In [451]:
#Applying the standard scaler function to all columns
from sklearn.preprocessing import StandardScaler

#data=  data.ffill()
scaler= StandardScaler()

# Applying the standard scaler function to Net Liquidity column
data['CPI Inflation'] = scaler.fit_transform(data[['CPI Inflation']])
data.head()

,Repo,CPI Inflation,91d yield,182d yield,364d yield,1y G-sec,3y G-sec,5y G-sec,10y G-sec,MCLR,quarter,Month
Date,,,,,,,,,,,,
2020-05-01,4.4,-1.779440,3.368250,3.621600,3.654900,3.98,4.39,4.97,5.98,7.80,1,5
2020-06-01,4.0,-1.714090,3.311025,3.463500,3.558075,3.73,4.35,5.07,5.99,7.65,1,6
2020-07-01,4.0,-1.561607,3.217400,3.372500,3.456460,3.58,4.73,4.99,5.84,7.60,2,7
2020-08-01,4.0,-1.503518,3.234050,3.426525,3.540425,3.75,4.99,5.48,6.08,7.60,2,8
2020-09-01,4.0,-1.380079,3.275150,3.526025,3.655025,3.71,4.95,5.39,6.02,7.55,2,9

In [452]:
exog_cols = ['Repo', 'CPI Inflation',  '91d yield', '182d yield', '364d yield',
             '1y G-sec', '3y G-sec', '5y G-sec', '10y G-sec', 'quarter','Month'] 

# Fit Auto ARIMA model
model = auto_arima(data['MCLR'],  X= data[exog_cols], seasonal=True, m=12, d=1, test='adf',trace=True,stepwise=True, D=None) #test='adf'

Performing stepwise search to minimize aic
 ARIMA(2,1,2)(1,0,1)[12] intercept   : AIC=-186.059, Time=0.81 sec
 ARIMA(0,1,0)(0,0,0)[12] intercept   : AIC=-175.919, Time=0.34 sec
 ARIMA(1,1,0)(1,0,0)[12] intercept   : AIC=-194.729, Time=0.67 sec
 ARIMA(0,1,1)(0,0,1)[12] intercept   : AIC=-185.884, Time=0.60 sec
 ARIMA(0,1,0)(0,0,0)[12]             : AIC=-173.152, Time=0.17 sec
 ARIMA(1,1,0)(0,0,0)[12] intercept   : AIC=-197.031, Time=0.34 sec
 ARIMA(1,1,0)(0,0,1)[12] intercept   : AIC=-194.529, Time=0.50 sec
 ARIMA(1,1,0)(1,0,1)[12] intercept   : AIC=-191.677, Time=0.56 sec
 ARIMA(2,1,0)(0,0,0)[12] intercept   : AIC=-194.901, Time=0.34 sec
 ARIMA(1,1,1)(0,0,0)[12] intercept   : AIC=-193.770, Time=0.36 sec
 ARIMA(0,1,1)(0,0,0)[12] intercept   : AIC=-186.866, Time=0.38 sec
 ARIMA(2,1,1)(0,0,0)[12] intercept   : AIC=-192.614, Time=0.40 sec
 ARIMA(1,1,0)(0,0,0)[12]             : AIC=-198.065, Time=0.35 sec
 ARIMA(1,1,0)(1,0,0)[12]             : AIC=-196.225, Time=0.56 sec
 ARIMA(1,1,0)(0,0,1)[12]             : AIC=-195.720, Time=0.45 sec
 ARIMA(1,1,0)(1,0,1)[12]             : AIC=-194.217, Time=0.55 sec
 ARIMA(2,1,0)(0,0,0)[12]             : AIC=-195.563, Time=0.38 sec
 ARIMA(1,1,1)(0,0,0)[12]             : AIC=-194.571, Time=0.37 sec
 ARIMA(0,1,1)(0,0,0)[12]             : AIC=-185.838, Time=0.32 sec
 ARIMA(2,1,1)(0,0,0)[12]             : AIC=-194.267, Time=0.37 sec

Best model:  ARIMA(1,1,0)(0,0,0)[12]
Total fit time: 8.862 seconds

In [453]:
# Print model summary
print(model.summary())

                               SARIMAX Results
==============================================================================
Dep. Variable:                      y   No. Observations:                   62
Model:               SARIMAX(1, 1, 0)   Log Likelihood                 112.033
Date:                Fri, 12 Sep 2025   AIC                           -198.065
Time:                        14:25:20   BIC                           -170.624
Sample:                    05-01-2020   HQIC                          -187.311
                         - 06-01-2025
Covariance Type:                  opg
=================================================================================
                    coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------
Repo              0.1293      0.040      3.259      0.001       0.052       0.207
CPI Inflation    -0.0485      0.082     -0.590      0.555      -0.210       0.113
91d yield         0.0281      0.073      0.383      0.702      -0.116       0.172
182d yield       -0.1718      0.203     -0.845      0.398      -0.570       0.227
364d yield        0.0688      0.169      0.406      0.684      -0.263       0.401
1y G-sec          0.0284      0.034      0.842      0.400      -0.038       0.094
3y G-sec          0.0397      0.060      0.666      0.505      -0.077       0.157
5y G-sec          0.0070      0.079      0.090      0.929      -0.147       0.161
10y G-sec        -0.0106      0.114     -0.093      0.926      -0.233       0.212
quarter          -0.0069      0.009     -0.767      0.443      -0.025       0.011
Month            -0.0018      0.002     -0.822      0.411      -0.006       0.003
ar.L1             0.6860      0.121      5.655      0.000       0.448       0.924
sigma2            0.0014      0.000      3.908      0.000       0.001       0.002
===================================================================================
Ljung-Box (L1) (Q):                   0.20   Jarque-Bera (JB):                26.38
Prob(Q):                              0.65   Prob(JB):                         0.00
Heteroskedasticity (H):               1.40   Skew:                             1.00
Prob(H) (two-sided):                  0.46   Kurtosis:                         5.53
===================================================================================

Warnings:
[1] Covariance matrix calculated using the outer product of gradients (complex-step).

In [454]:
def Future_independet_Variables(h24):
    Future_Date = pd.date_range(start=h24.index[-1], periods=6, freq='MS')
    Future_Date=Future_Date[1:]
    Future=pd.DataFrame({"Date":Future_Date})
    Future=Future.set_index("Date")
    Future['Repo']=h24['Repo'][-1]
    Future['CPI Inflation']=h24['CPI Inflation'][-1]
    Future['91d yield']=h24['91d yield'][-1]
    Future['182d yield']=h24['182d yield'][-1]
    Future['364d yield']=h24['364d yield'][-1]
    Future['1y G-sec']=h24['1y G-sec'][-1]
    Future['3y G-sec']=h24['3y G-sec'][-1]
    Future['5y G-sec']=h24['5y G-sec'][-1]
    Future['10y G-sec']=h24['10y G-sec'][-1]
    Future['quarter']=h24['quarter'][-1] 
    Future['Month']=h24['Month'][-1]   

    
    Future= Merging_feature_engg_with_data(Future)
    return Future

future_exog= Future_independet_Variables(data)

C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['Repo']=h24['Repo'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:7: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['CPI Inflation']=h24['CPI Inflation'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:8: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['91d yield']=h24['91d yield'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:9: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['182d yield']=h24['182d yield'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:10: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['364d yield']=h24['364d yield'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['1y G-sec']=h24['1y G-sec'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:12: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['3y G-sec']=h24['3y G-sec'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['5y G-sec']=h24['5y G-sec'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:14: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['10y G-sec']=h24['10y G-sec'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:15: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['quarter']=h24['quarter'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\1054139215.py:16: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  Future['Month']=h24['Month'][-1]
C:\Users\manirathinams\AppData\Local\Temp\ipykernel_31700\3578216625.py:14: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value 'Q4' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  data.loc[data['quarter']==1,'quarter']='Q4'

In [455]:
# Get forecast
#forecast_steps = 26 Number of steps to forecast into the future

forecast, conf_int = model.predict(n_periods=len(future_exog), X= future_exog, return_conf_int=True)

In [456]:
forecast
# Dataframe for forecasted data
preds= pd.DataFrame(forecast, columns=['Forecasted'])
preds

            Forecasted
2025-07-01    8.892218
2025-08-01    8.891041
2025-09-01    8.889657
2025-10-01    8.881226
2025-11-01    8.879603